pipeline {
        agent { label 'python_agent' }
        stages {
            stage('Setup') {
                steps {
                    echo "Running ${env.BUILD_ID} with workspace ${env.WORKSPACE}"

                    sh 'python3 -m venv venv'
                    sh 'venv/bin/pip install coverage'
                }
            }
            stage('Build') {
                steps {
                    sh 'venv/bin/pip install -r analyzer/requirements.txt'
                    
                }
            }
            stage('Python Lint') {
                steps {
                    sh 'pylint --fail-under=5 analyzer/*.py'
                }
            }
            stage('Security Stage') {
                steps {
                    echo "security"
                }
            }
            stage('Package') {
                // when {
                //     expression { env.GIT_BRANCH == 'origin/main' }
                // }
                // steps {
                //     withCredentials([string(credentialsId: 'DockerHub', variable: 'TOKEN')]) {
                //         sh "docker login -u 'jparras1' -p '$TOKEN' docker.io"
                //         sh "docker build -t ${dockerRepoName}:latest --tag jparras1/${dockerRepoName}:${imageName} ."
                //         sh "docker push jparras1/${dockerRepoName}:${imageName}"
                //     }
                // }
                steps {
                    echo "package"
                }
            }
        }
    }